# Generated by Django 3.2.13 on 2023-03-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adi', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logolar/')),
                ('instagram_adresi', models.URLField(blank=True)),
                ('twitter_adresi', models.URLField(blank=True)),
                ('facebook_adresi', models.URLField(blank=True)),
                ('is_yeri_adresi', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
