# Generated by Django 3.2.13 on 2023-03-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230329_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='facebook_adresi',
        ),
        migrations.RemoveField(
            model_name='site',
            name='instagram_adresi',
        ),
        migrations.RemoveField(
            model_name='site',
            name='is_yeri_adresi',
        ),
        migrations.RemoveField(
            model_name='site',
            name='twitter_adresi',
        ),
    ]
