# Generated by Django 3.2.13 on 2023-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20230329_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/'),
        ),
    ]
