# Generated by Django 3.2.13 on 2023-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20230330_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='noimages.png', upload_to='category_images'),
        ),
    ]
